Repository puppetlabs/puppetlabs-ntp, pull requests merged in 2018-12, with the labels that each got.

#492 (MODULES-8139) - Add SLES 15 support
  metadata.json
  spec/acceptance/ntp_service_spec.rb
Labels: feature

#493 pdksync - pdksync_heads/master-0-gbf720df
  .gitattributes
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#495 pdksync - (FM-7655) Fix rubygems-update for ruby < 2.3
  .travis.yml
  metadata.json
Labels: bugfix

#494 (maint) Add HTML anchor tag
  README.md
Labels: maintenance
