Repository puppetlabs/puppetlabs-ntp, pull requests merged in 2019-06, with the labels that each got.

#516 pdksync - MODULES-9057 Fix the module contribution guide link
  README.md
Labels: maintenance

#518 pdksync - pdksync_heads/master-0-g7827fc2
  .rubocop.yml
  .travis.yml
  .vscode/extensions.json
  Gemfile
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#517 (FM-8188) convert ntp to use litmus
  .fixtures.yml
  .sync.yml
  .travis.yml
  Gemfile
  README.md
  Rakefile
  distelli-manifest.yml
  provision.yaml
  spec/acceptance/ntp_parameters_spec.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature

#521 Fix disable_dhclient
  manifests/config.pp
Labels: bugfix
