Repository puppetlabs/puppetlabs-ntp, pull requests merged in 2019-12, with the labels that each got.

#544 pdksync - FM-8499 remove ubuntu 14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#545 pdksync - "MODULES-10242 Add ubuntu14 support back to the modules"
  metadata.json
  provision.yaml
Labels: feature

#546 pdksync - "MODULES-10236 disable deploy_to_forge for the module"
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#547 (maint) Release MergeBack version v8.2.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#548 pdksync - (maint) travis updates: bundler and slack
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#550 pdksync - FM-8834 - Add GitHub action workflow
  .github/workflows/release.yml
Labels: maintenance
