Repository puppetlabs/puppetlabs-ntp, pull requests merged in 2023-07, with the labels that each got.

#678 Avoid hardcoding year values
  spec/acceptance/integration_ntp_spec.rb
Labels: maintenance, MayTheSourceBeWithYou

#691 (CONT-1151) erb to epp template conversion
  REFERENCE.md
  data/common.yaml
  manifests/config.pp
  manifests/init.pp
  readmes/README_ja_JP.md
  spec/acceptance/ntp_parameters_spec.rb
  spec/classes/ntp_spec.rb
  spec/fixtures/my_ntp/templates/ntp.conf.erb
Labels: backwards-incompatible

#693 pdksync - (maint) - Replace legacy facts in spec/default_facts.yml
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#694 pdksync - (CONT-1219) - fail ci for puppetlabs members if no label
  .github/workflows/labeller.yml
Labels: maintenance

#695 (CAT-1204) - CI pipeline fix for SLES OS
  manifests/install.pp
Labels: maintenance
